#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProc=$(getNumberOfProcessors)

runApplication blockMesh

runApplication decomposePar

runParallel pisoTurbinesFoam $nProc

runApplication reconstructPar

rm -rf processor*
