#!/usr/bin/env bash
# Check code style using vera++

# Check source files
find . -path "*lnInclude*" -prune -o -name "*.C" -print | vera++

# Check headers
find . -path "*lnInclude*" -prune -o -name "*.H" -print | vera++
