#!/usr/bin/env bash

./Allwmake

startDir=$PWD

if [ $1 ]
then
    app=$1
else
    app="pimpleFoam"
fi

cd tutorials/$app/actuatorLine

#cp -rf 0.org 0
#blockMesh
#snappyHexMesh -overwrite
#topoSet
$app

#./Allclean

cd $startDir
