#!/usr/bin/env bash

./Allwmake

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

startDir=$PWD

if [ $1 ]
then
    app=$1
else
    app="pimpleFoam"
fi

cd tutorials/actuatorLine/$app

# Pre-process case only if necessary
if [ ! -f log.snappyHexMesh ]; then
    cp -rf 0.org 0
    runApplication blockMesh
    runApplication snappyHexMesh -overwrite
    runApplication topoSet
fi

$app

cd $startDir
