#!/usr/bin/env bash

./Allwmake

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

startDir=$PWD

cd tutorials/crossFlowTurbineAL

# Pre-process case only if necessary
if [ ! -f log.snappyHexMesh ]; then
    cp -rf 0.org 0
    runApplication blockMesh
    runApplication snappyHexMesh -overwrite
    runApplication topoSet
fi

pimpleFoam

cd $startDir
