#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh -dict system/blockMeshDict-3D
runApplication snappyHexMesh -overwrite
runApplication topoSet

if [ "$1" = "-parallel" ]
    then
    python scripts/set_alpha.py $2 -d
    if [ $WM_PROJECT_VERSION = "dev" ]
        then
        nProc=""
    else
        nProc=$(getNumberOfProcessors)
    fi
    runApplication decomposePar
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
    runParallel $nProc simpleFoam
    runApplication reconstructPar
    rm -rf processor*
else
    python scripts/set_alpha.py $1 -d
    runApplication simpleFoam
fi
