name: Run tests

on: pull_request

jobs:
  test-esi:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [2206, 2212, 2306, 2312, 2406]
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenFOAM
        uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: ${{ matrix.version }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Python dependencies
        run: pip install pandas nose numpy
      - name: Compile
        run: ./Allwmake
      - name: Run tests
        run: ./Alltest
  test-foundation:
    if: false # Skip because library has diverged
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [8]
    steps:
      - uses: actions/checkout@v4
      - name: Add OpenFOAM GPG key
        run: sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
      - name: Add OpenFOAM apt repository
        run: sudo add-apt-repository http://dl.openfoam.org/ubuntu
      - name: Install OpenFOAM
        run: sudo apt update && sudo apt -yq install openfoam${{ matrix.version }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Python dependencies
        run: pip install pandas nose numpy
      - name: Compile
        run: source /opt/openfoam${{ matrix.version }}/etc/bashrc && ./Allwmake
      - name: Run tests
        run: source /opt/openfoam${{ matrix.version }}/etc/bashrc && ./Alltest
